version: '3.9'

services:
  
  web:
    container_name: my-awesome-app-eag-aws
    image: eagiov89/my-awesome-app-eag:latest
    ports:
    - '80:8080'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules