name: Docker Dev Image CI

env:
  DATE_STAMP: $(date +%s)

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Env variables
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB

      - name: Run Docker compose on Dev files
        run: docker-compose -f "docker-compose-dev.yml" up -d --build web

      - name: Add "date-stamp" tag to the image
        run: docker image tag eagiov89/my-awesome-web-dev:latest eagiov89/my-awesome-web-dev:${{env.date-stamp}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push the Docker image to Docker Hub
        run: docker push --all-tags eagiov89/my-awesome-web-dev
      

